"""US Fundamentals — categorized BBG ticker inventory with analytical use cases.

Curated from the deep US-economy research. Every entry: ticker, BBG bucket, category,
subcategory, proper name (from BBG ticker dictionary where available), and a one-line
analytical use case for STIR/Bond decisions.
"""
from __future__ import annotations

from typing import TypedDict


class TickerEntry(TypedDict):
    ticker: str
    bucket: str          # parquet folder
    category: str        # top-level group
    subcategory: str     # finer group
    name: str            # human-readable
    analysis: str        # one-line trader-relevant use case


# -----------------------------------------------------------------------------
# Helper to keep the data table readable
# -----------------------------------------------------------------------------
def E(ticker, bucket, category, subcategory, name, analysis) -> TickerEntry:
    return TickerEntry(ticker=ticker, bucket=bucket, category=category,
                       subcategory=subcategory, name=name, analysis=analysis)


# Categories (ordered for display)
CATEGORIES = [
    "Policy Rates & Monetary Ops",
    "Cash Yield Curve",
    "Inflation",
    "Employment & Labor",
    "Growth & Output",
    "Consumer",
    "Housing",
    "Business & Factory",
    "Trade & External",
    "Fed Regional Surveys",
    "Fiscal / Treasury Operations",
    "Treasury Auctions",
    "Energy",
    "Agriculture",
    "Volatility",
    "Credit",
    "FX",
    "Equity Indices",
    "Positioning (CFTC COT)",
]


# =============================================================================
# THE INVENTORY
# =============================================================================
US_TICKERS: list[TickerEntry] = [

    # =========================================================================
    # POLICY RATES & MONETARY OPS
    # =========================================================================
    E("FDTR Index",       "rates_drivers", "Policy Rates & Monetary Ops", "Fed Policy Rate Direct",
      "Federal Funds Target Rate — Upper Bound",
      "THE policy rate. Anchor for SRA / S1R / FF. Every basis point drives the entire STIR curve."),
    E("FDTRFTRL Index",   "eco",           "Policy Rates & Monetary Ops", "Fed Policy Rate Direct",
      "Federal Funds Target Rate — Lower Bound",
      "Lower bound of band. FF futures settle to mid of (FDTR upper + FDTRFTRL lower)."),
    E("FDTRMID Index",    "rates_drivers", "Policy Rates & Monetary Ops", "Fed Policy Rate Direct",
      "Federal Funds Target Mid (band midpoint)",
      "The actual settlement reference for FF futures."),
    E("FDFD Index",       "rates_drivers", "Policy Rates & Monetary Ops", "Fed Effective Rate",
      "Federal Funds Effective Rate (NY Fed daily)",
      "Realized rate. FFER vs SOFR spread = unsecured-secured funding tension; FF settles on monthly avg of this."),
    E("IRRBIOER Index",   "eco",           "Policy Rates & Monetary Ops", "Reserve Remuneration",
      "US Federal Reserve Interest on Reserve Balances (IORB)",
      "Floor for Fed Funds — banks won't lend below this. Sets effective lower bound on FFER."),
    E("SOFRRATE Index",   "rates_drivers", "Policy Rates & Monetary Ops", "SOFR — Money Market",
      "Secured Overnight Financing Rate (SOFR)",
      "THE underlying for SRA (3M comp) and S1R (1M arith). Settlement reference."),
    E("SOFRINDX Index",   "rates_drivers", "Policy Rates & Monetary Ops", "SOFR — Money Market",
      "SOFR Compounded Index",
      "Used for in-arrears settlement of SOFR futures and floating-rate notes."),
    E("FARBAST Index",    "rates_drivers", "Policy Rates & Monetary Ops", "Fed Balance Sheet",
      "Federal Reserve Bank Total Assets (H.4.1)",
      "QT pace = supply pressure on belly/long-end. Bigger = bull-flatten bias; shrinking = bear-steepen."),
    E("FEDMMINU Index",   "eco",           "Policy Rates & Monetary Ops", "FOMC Communications",
      "FOMC Meeting Minutes Release",
      "3-week-lagged release. Reveals dissents, dot rationale, balance-sheet plans → Day-1 STIR repricing."),
    E("FFCAB12S Index",   "eco",           "Policy Rates & Monetary Ops", "Fed Surveys",
      "Fed forecast / 12-month consumer expectations",
      "Fed-released expectations indicator. Used as policy-guidance signal."),
    E("FRBDEURO Index",   "eco",           "Policy Rates & Monetary Ops", "Fed Cross-Reference",
      "Fed Reserve / Euro reference series",
      "Cross-rate context for Fed in international monetary system."),

    # =========================================================================
    # CASH YIELD CURVE
    # =========================================================================
    E("USGG2YR Index",    "rates_drivers", "Cash Yield Curve", "Treasury Yield",
      "US Generic 2Y Treasury Yield",
      "Cash side of TU. Most-correlated with Fed cycle; leads policy turns 6-9 months."),
    E("USGG5YR Index",    "rates_drivers", "Cash Yield Curve", "Treasury Yield",
      "US Generic 5Y Treasury Yield",
      "Cash side of FV. Belly tenor; PCA-PC2 (slope) loadings concentrate here."),
    E("USGG10YR Index",   "rates_drivers", "Cash Yield Curve", "Treasury Yield",
      "US Generic 10Y Treasury Yield",
      "Cash side of TY. THE benchmark; recession indicator input."),
    E("USGG30YR Index",   "rates_drivers", "Cash Yield Curve", "Treasury Yield",
      "US Generic 30Y Treasury Yield",
      "Cash side of AUL. Long-end risk premium; convexity / supply/demand dominant."),
    E("USYC2Y10 Index",   "credit",        "Cash Yield Curve", "Curve Direct",
      "US Treasury 2s10s Yield Curve Spread",
      "THE recession gauge. Inversion → 12-18mo recession lead → STIR cuts pricing."),

    # =========================================================================
    # INFLATION
    # =========================================================================
    # Headline CPI
    E("CPI YOY Index",    "eco", "Inflation", "Headline CPI",
      "US CPI Urban Consumers YoY NSA",
      "#1 BOND mover. 8:30 ET 2nd week of month. Surprise vs. survey moves yields 5-15 bp."),
    E("CPI CHNG Index",   "eco", "Inflation", "Headline CPI",
      "US CPI Urban Consumers MoM SA",
      "Monthly change for trajectory; intramonth vol indicator."),
    E("CPURNSA Index",    "eco", "Inflation", "Headline CPI",
      "US CPI Urban Consumers NSA (level)",
      "Index level — useful for tracking CPI level path vs Fed's 2% objective in basket terms."),
    E("CPUPXCHG Index",   "eco", "Inflation", "Headline CPI",
      "US CPI Urban Consumers Less Food MoM",
      "Less-food MoM variant; food noise removed."),
    E("CPIXBREX Index",   "eco", "Inflation", "Core CPI Variant",
      "US CPI ex food/energy/shelter",
      "'Supercore' alternative — strips most volatile components, isolates services inflation."),
    # Core CPI
    E("CPI XYOY Index",   "eco", "Inflation", "Core CPI",
      "US CPI Urban Consumers Less Food & Energy YoY",
      "Fed's structural inflation gauge — dictates dot-plot moves."),
    E("CPUPAXFE Index",   "eco", "Inflation", "Core CPI",
      "US CPI ex Food & Energy YoY (alt formulation)",
      "Cross-check on core measure."),
    E("CRCIMOM Index",    "eco", "Inflation", "Core CPI",
      "Core CPI MoM",
      "Monthly core for trajectory."),
    E("CRCIYOY Index",    "eco", "Inflation", "Core CPI",
      "Core CPI YoY (alt)",
      "Cross-check formulation."),
    E("PIRBCPIM Index",   "eco", "Inflation", "Regional CPI Variant",
      "Regional Fed PI / CPI deflator MoM",
      "Sub-national inflation indicator; useful for cross-checks against headline."),
    E("PIRBCPIY Index",   "eco", "Inflation", "Regional CPI Variant",
      "Regional PI / CPI deflator YoY",
      "YoY companion to PIRBCPIM."),
    # PPI
    E("FDIDFDMO Index",   "eco", "Inflation", "PPI Headline",
      "US PPI Final Demand MoM SA",
      "Producer pipeline — leads CPI by 1-2 months."),
    E("FDIUFDYO Index",   "eco", "Inflation", "PPI Headline",
      "US PPI Final Demand YoY NSA",
      "YoY headline producer inflation."),
    E("FDIDSGMO Index",   "eco", "Inflation", "PPI Core",
      "US PPI Final Demand Less Foods & Energy MoM",
      "Core PPI MoM — services-component significant."),
    E("FDIDSGUM Index",   "eco", "Inflation", "PPI Core",
      "US PPI Final Demand Less Foods & Energy & Trade Services MoM",
      "Cleanest core PPI — strips most volatile pass-through items."),
    E("FDIUSGYO Index",   "eco", "Inflation", "PPI Core",
      "US PPI Final Demand Less Foods & Energy YoY",
      "Core PPI YoY."),
    E("FDIUSGUY Index",   "eco", "Inflation", "PPI Core",
      "US PPI Final Demand Less Foods & Energy & Trade YoY",
      "Cleanest core PPI YoY."),
    E("PIRBIPIM Index",   "eco", "Inflation", "Industrial Pricing",
      "Industrial Price Index MoM",
      "Producer pipeline (proxy for PPI manufacturing piece)."),
    E("PIRBIPIY Index",   "eco", "Inflation", "Industrial Pricing",
      "Industrial Price Index YoY",
      "YoY industrial."),
    # Imported / Exported
    E("IMP1CHNG Index",   "eco", "Inflation", "Import Prices",
      "US Import Price Index MoM",
      "Imported inflation channel; FX-linked CPI driver."),
    E("IMP1XPM% Index",   "eco", "Inflation", "Import Prices",
      "US Import Price Index ex Petroleum %",
      "Cleanest non-oil imported inflation gauge."),
    E("IMP1YOY% Index",   "eco", "Inflation", "Import Prices",
      "US Import Price Index YoY",
      "YoY import-side inflation."),
    E("EXP1CMOM Index",   "eco", "Inflation", "Export Prices",
      "US Export Price By End Use All Commodities MoM",
      "US export pricing power; reflects external demand strength."),
    E("EXP1CYOY Index",   "eco", "Inflation", "Export Prices",
      "US Export Price By End Use All Commodities YoY",
      "YoY export pricing."),
    # Inflation expectations
    E("CONSPXMD Index",   "eco", "Inflation", "Inflation Expectations",
      "UMich 1-Year Inflation Expectations",
      "Short-run anchor; biases STIR repricing on print day."),
    E("CONSP5MD Index",   "eco", "Inflation", "Inflation Expectations",
      "UMich 5-Year Inflation Expectations",
      "Long-run anchor — Fed-watched closely for 'de-anchoring' regime."),
    E("NYCNM1IR Index",   "eco", "Inflation", "Inflation Expectations",
      "NY Fed 1Y Inflation Expectations Median (SCE)",
      "Independent measure; increasingly Fed-cited; high-frequency monthly read."),

    # =========================================================================
    # EMPLOYMENT & LABOR MARKET
    # =========================================================================
    E("NFP TCH Index",    "eco", "Employment & Labor", "Establishment Survey",
      "US Non-Farm Payrolls Total Change",
      "#1 STIR mover. 1st Friday 8:30 ET. Surprise drives 10-30bp same-day yield moves."),
    E("NFP PCH Index",    "eco", "Employment & Labor", "Establishment Survey",
      "US Non-Farm Payrolls Private",
      "Private NFP — strips government noise; cleaner private-sector signal."),
    E("ADP CHNG Index",   "eco", "Employment & Labor", "Establishment Survey",
      "ADP National Employment Report",
      "NFP preview, 2 days before. ADP-NFP spread = forecast error indicator."),
    E("AHE MOM% Index",   "eco", "Employment & Labor", "Wage Inflation",
      "US Average Hourly Earnings MoM",
      "Wage-inflation pulse — released with NFP."),
    E("AHE YOY% Index",   "eco", "Employment & Labor", "Wage Inflation",
      "US Average Hourly Earnings YoY",
      "Trend wage growth — feeds Fed reaction function."),
    E("AWH TOTL Index",   "eco", "Employment & Labor", "Hours Worked",
      "US Average Weekly Hours All Employees",
      "Hours = labor input intensity. Falling = recessionary; rising = tight labor market."),
    E("INJCJC Index",     "eco", "Employment & Labor", "Real-Time Labor",
      "US Initial Jobless Claims SA",
      "THE high-frequency US labor signal — weekly Thu 8:30 ET."),
    E("INJCSP Index",     "eco", "Employment & Labor", "Real-Time Labor",
      "US Continuing Jobless Claims SA",
      "Lagging — measures hiring frictions; rising = harder to find work."),
    E("JOLTOPEN Index",   "eco", "Employment & Labor", "Labor Demand (JOLTS)",
      "US Job Openings Rate SA",
      "Labor demand level — Fed-watched (vacancy/UR ratio key)."),
    E("JOLTQUIS Index",   "eco", "Employment & Labor", "Labor Demand (JOLTS)",
      "US Quits Rate SA",
      "Worker confidence — leads wage growth ~3 months."),
    E("JOLTLAYS Index",   "eco", "Employment & Labor", "Labor Demand (JOLTS)",
      "US Layoffs & Discharge Rate SA",
      "Firing intensity."),
    E("JOLTTOTL Index",   "eco", "Employment & Labor", "Labor Demand (JOLTS)",
      "US Job Openings By Industry Total",
      "Aggregate openings count."),
    E("JLTSLAYS Index",   "eco", "Employment & Labor", "Labor Demand (JOLTS)",
      "JOLTS Layoffs (alt formulation)",
      "Alternative JOLTS layoffs measure for cross-check."),
    E("JLTSQUIS Index",   "eco", "Employment & Labor", "Labor Demand (JOLTS)",
      "JOLTS Quits (alt formulation)",
      "Alternative JOLTS quits measure."),
    E("CHALYOY% Index",   "eco", "Employment & Labor", "Layoffs Tracking",
      "Challenger US Job Cut Announcements YoY",
      "Monthly announced layoffs — leading indicator for INJCJC."),
    E("ECONGECC Index",   "eco", "Employment & Labor", "Payroll Revisions",
      "Net Revisions to Nonfarm Payrolls (BLS QCEW benchmark)",
      "Annual QCEW revision; can move STIR 5-15bp on release."),
    E("PRUSTOT Index",    "eco", "Employment & Labor", "Productivity",
      "US Productivity Total",
      "Output-per-hour. ULC = wages/productivity → unit cost inflation."),

    # =========================================================================
    # GROWTH & OUTPUT
    # =========================================================================
    # GDP
    E("GDP CQOQ Index",   "eco", "Growth & Output", "GDP",
      "GDP US Chained Dollars QoQ SAAR",
      "Headline growth rate — quarterly (advance/preliminary/final)."),
    E("GDP PIQQ Index",   "eco", "Growth & Output", "GDP",
      "US GDP Price Index QoQ SAAR",
      "Implicit deflator — alternative inflation gauge."),
    E("GDPCPCEC Index",   "eco", "Growth & Output", "GDP",
      "US GDP Personal Consumption Core",
      "PCE component (Fed's preferred deflator basis)."),
    E("GDPCTOT% Index",   "eco", "Growth & Output", "GDP",
      "GDP Personal Consumption Total Change",
      "Total PCE growth — main GDP driver."),
    # Industrial Production
    E("IP CHNG Index",    "eco", "Growth & Output", "Industrial Production",
      "US Industrial Production MoM SA",
      "Output gap input — manufacturing/utilities/mining composite."),
    E("IPMGCHNG Index",   "eco", "Growth & Output", "Industrial Production",
      "US Industrial Production Manufacturing",
      "Manufacturing sector only — cyclical."),
    E("CPTICHNG Index",   "eco", "Growth & Output", "Capacity Utilization",
      "US Capacity Utilization % of Total",
      "Slack measure — high util → wage/price pressure."),
    # ISM
    E("NAPMPMI Index",    "eco", "Growth & Output", "ISM Manufacturing",
      "ISM Manufacturing PMI SA",
      "Headline mfg index — 50 = growth threshold."),
    E("NAPMNEWO Index",   "eco", "Growth & Output", "ISM Manufacturing",
      "ISM Manufacturing New Orders",
      "Forward-looking demand component."),
    E("NAPMEMPL Index",   "eco", "Growth & Output", "ISM Manufacturing",
      "ISM Manufacturing Employment",
      "Mfg labor demand."),
    E("NAPMPRIC Index",   "eco", "Growth & Output", "ISM Manufacturing",
      "ISM Manufacturing Prices Paid",
      "Pipeline inflation — leads PPI by 1-2 months."),
    E("NAPMNMI Index",    "eco", "Growth & Output", "ISM Services",
      "ISM Services PMI",
      "Services dominant in US economy."),
    E("NAPMNNO Index",    "eco", "Growth & Output", "ISM Services",
      "ISM Services New Orders",
      "Services demand pipeline."),
    E("NAPMNEMP Index",   "eco", "Growth & Output", "ISM Services",
      "ISM Services Employment",
      "Services labor demand."),
    E("NAPMNPRC Index",   "eco", "Growth & Output", "ISM Services",
      "ISM Services Prices Paid",
      "Services-side inflation."),
    # S&P Global PMI
    E("MPMIUSMA Index",   "eco", "Growth & Output", "S&P Global PMI",
      "US Manufacturing PMI SA",
      "Independent confirmation of ISM."),
    E("MPMIUSSA Index",   "eco", "Growth & Output", "S&P Global PMI",
      "US Services PMI Business Activity SA",
      "Services PMI cross-check."),
    E("MPMIUSCA Index",   "eco", "Growth & Output", "S&P Global PMI",
      "US Composite PMI SA",
      "Aggregate composite — single composite read."),
    # Capital Goods
    E("CGNOXAI% Index",   "eco", "Growth & Output", "Capital Goods (Capex Proxy)",
      "Capital Goods New Orders Nondefense Ex Aircraft",
      "Core capex proxy — best business-investment leading indicator."),
    E("CGSHXAI% Index",   "eco", "Growth & Output", "Capital Goods (Capex Proxy)",
      "Capital Goods Shipments Nondefense Ex Aircraft",
      "Capex actually delivered — feeds GDP investment line."),
    # Composite Leading
    E("LEI CHNG Index",   "eco", "Growth & Output", "Composite Leading Indicators",
      "Conference Board US Leading Economic Indicators",
      "10-component composite — recession lead indicator."),
    E("CFNAI Index",      "eco", "Growth & Output", "Composite Leading Indicators",
      "Chicago Fed National Activity Index",
      "85-component composite — best single activity gauge."),

    # =========================================================================
    # CONSUMER
    # =========================================================================
    E("CONCCONF Index",   "eco", "Consumer", "Conference Board Sentiment",
      "Conference Board Consumer Confidence Index",
      "Headline consumer mood — biases discretionary spending."),
    E("CONCEXP Index",    "eco", "Consumer", "Conference Board Sentiment",
      "Conf Board Consumer Expectations",
      "Forward-looking sub-index."),
    E("CONCPSIT Index",   "eco", "Consumer", "Conference Board Sentiment",
      "Conf Board Present Situation",
      "Current conditions."),
    E("CONSSENT Index",   "eco", "Consumer", "UMich Sentiment",
      "University of Michigan Consumer Sentiment Index",
      "Long-running parallel measure to Conf Board CCI."),
    E("CONSCURR Index",   "eco", "Consumer", "UMich Sentiment",
      "UMich Current Conditions",
      "Now state."),
    E("CONSEXP Index",    "eco", "Consumer", "UMich Sentiment",
      "UMich Consumer Expectations",
      "Forward outlook."),
    E("CICRTOT Index",    "eco", "Consumer", "Consumer Credit",
      "Federal Reserve Consumer Credit Outstanding Total",
      "Household leverage gauge — credit-cycle stage."),

    # =========================================================================
    # HOUSING
    # =========================================================================
    E("NHSPATOT Index",   "eco", "Housing", "Building Permits",
      "Private Total Housing Authorized by Permit",
      "Most forward-looking housing indicator; rate-sensitive."),
    E("NHSPSTOT Index",   "eco", "Housing", "Building Permits",
      "US New Privately Owned Housing Authorizations Total",
      "SA permits total."),
    E("NHCHATCH Index",   "eco", "Housing", "Construction Activity",
      "Private Total Housing Authorized Change",
      "Authorization change MoM."),
    E("NHCHSTCH Index",   "eco", "Housing", "Construction Activity",
      "Private Housing Units Started Change",
      "Construction-activity change MoM."),
    E("NHSLCHNG Index",   "eco", "Housing", "New Home Sales",
      "US New One Family Houses Sold Change",
      "Demand pulse MoM."),
    E("NHSLTOT Index",    "eco", "Housing", "New Home Sales",
      "US New One Family Houses Sold Total",
      "Level."),
    E("ETSLMOM Index",    "eco", "Housing", "Existing Home Sales",
      "US Existing Homes Sales MoM SA",
      "NAR existing-home sales MoM (largest housing-demand indicator)."),
    E("ETSLTOTL Index",   "eco", "Housing", "Existing Home Sales",
      "US NAR Total Existing Homes Sales",
      "Total NAR existing sales."),
    E("MBAVCHNG Index",   "eco", "Housing", "Mortgage Activity",
      "MBA US Mortgage Market Index Change",
      "Real-time housing demand vs. mortgage rates — weekly."),
    E("USHBMIDX Index",   "eco", "Housing", "Builder Sentiment",
      "NAHB Housing Market Index",
      "Builder sentiment for new construction."),
    E("HPIMMOM% Index",   "eco", "Housing", "House Prices",
      "FHFA US House Price Index Purchase MoM",
      "House-price inflation; feeds Owners-Equivalent Rent → core CPI (1-yr lag)."),
    E("CNSTTMOM Index",   "eco", "Housing", "Construction Spending",
      "Census Bureau US Construction Spending MoM",
      "Construction activity feeds GDP."),

    # =========================================================================
    # BUSINESS & FACTORY
    # =========================================================================
    E("DGNOCHNG Index",   "eco", "Business & Factory", "Durable Goods",
      "US Durable Goods New Orders MoM",
      "Big-ticket spending — capex proxy."),
    E("DGNOXTCH Index",   "eco", "Business & Factory", "Durable Goods",
      "US Durable Goods New Orders Ex Transportation",
      "Cleaner trend — strips noisy transport (aircraft)."),
    E("MTIBCHNG Index",   "eco", "Business & Factory", "Inventories",
      "US Manufacturing & Trade Inventories Change",
      "Inventory cycle stage."),
    E("MWINCHNG Index",   "eco", "Business & Factory", "Inventories",
      "Merchant Wholesalers Inventories Change",
      "Wholesale inventory cycle."),
    E("MWSLCHNG Index",   "eco", "Business & Factory", "Sales",
      "Merchant Wholesalers Sales Change",
      "Wholesale demand."),

    # =========================================================================
    # TRADE & EXTERNAL
    # =========================================================================
    E("FRNTTNET Index",   "eco", "Trade & External", "Foreign Capital Flows",
      "US Treasury International Capital (TIC) Net",
      "Net foreign flow into USD assets — UST demand from abroad."),
    E("FRNTTOTL Index",   "eco", "Trade & External", "Foreign Capital Flows",
      "US Foreign Net Transactions Total",
      "Foreign demand for UST aggregate measure."),

    # =========================================================================
    # FED REGIONAL SURVEYS
    # =========================================================================
    E("EMPRGBCI Index",   "eco", "Fed Regional Surveys", "NY Fed",
      "US Empire State Manufacturing",
      "Earliest regional release each month — Mid-Atlantic mfg signal."),
    E("NYBLCNBA Index",   "eco", "Fed Regional Surveys", "NY Fed",
      "US Business Leaders Survey Business Activity",
      "NY Fed services-side companion."),
    E("OUTFGAF Index",    "eco", "Fed Regional Surveys", "Philadelphia Fed",
      "Philadelphia Fed Business Outlook General Activity",
      "Mid-month Mid-Atlantic mfg signal."),
    E("PNMARADI Index",   "eco", "Fed Regional Surveys", "Philadelphia Fed",
      "Philly Fed Nonmanufacturing Outlook (NBOS)",
      "Services-side complement to OUTFGAF."),
    E("DFEDGBA Index",    "eco", "Fed Regional Surveys", "Dallas Fed",
      "Dallas Fed Manufacturing Activity",
      "Energy-belt cyclical."),
    E("DSERGBCC Index",   "eco", "Fed Regional Surveys", "Dallas Fed",
      "Texas Service Sector Outlook",
      "Services complement (Dallas)."),
    E("KCLSSACI Index",   "eco", "Fed Regional Surveys", "Kansas City Fed",
      "Kansas City Federal Reserve Manufacturing Composite",
      "Mid-continent mfg signal."),
    E("KCSSMCOM Index",   "eco", "Fed Regional Surveys", "Kansas City Fed",
      "Kansas City Services Survey Composite",
      "Mid-continent services."),
    E("AGECBARO Index",   "eco", "Fed Regional Surveys", "Agricultural Sentiment",
      "Purdue / CME Group Ag Economy Barometer",
      "Farmer sentiment — agricultural-belt confidence."),

    # =========================================================================
    # FISCAL / TREASURY OPS
    # =========================================================================
    E("FDDSSD Index",     "eco", "Fiscal / Treasury Operations", "Federal Budget",
      "US Treasury Federal Budget Deficit",
      "Monthly deficit. Bigger deficit → more issuance → bond supply → bear-steepen pressure."),

    # =========================================================================
    # TREASURY AUCTIONS — Bills (short-end)
    # =========================================================================
    # 4-Week Bill
    E("USB4WBC Index",    "eco", "Treasury Auctions", "4-Week Bill",
      "4W T-Bill Bid-to-Cover", "Demand strength at auction — < 2.5x = weak."),
    E("USB4WHYL Index",   "eco", "Treasury Auctions", "4-Week Bill",
      "4W T-Bill High Yield (auction stop)",
      "Stop-out yield. Tail vs WI yield = real-time UST appetite signal."),
    E("USB4DBA Index",    "eco", "Treasury Auctions", "4-Week Bill",
      "4W T-Bill Dealer Award", "Primary dealer absorption — high % = weak indirect demand."),
    E("USB4IBA Index",    "eco", "Treasury Auctions", "4-Week Bill",
      "4W T-Bill Indirect Award", "Foreign / asset-manager bid share."),
    # 8-Week Bill
    E("USB8WBC Index",    "eco", "Treasury Auctions", "8-Week Bill",
      "8W T-Bill Bid-to-Cover", "Demand strength."),
    E("USB8WHYL Index",   "eco", "Treasury Auctions", "8-Week Bill",
      "8W T-Bill High Yield", "Stop-out yield."),
    E("USB8DBAP Index",   "eco", "Treasury Auctions", "8-Week Bill",
      "8W T-Bill Dealer Award", "Dealer absorption."),
    E("USB8IBAP Index",   "eco", "Treasury Auctions", "8-Week Bill",
      "8W T-Bill Indirect Award", "Foreign demand."),
    # 13-Week Bill
    E("USB9WBC Index",    "eco", "Treasury Auctions", "13-Week Bill",
      "13W T-Bill Bid-to-Cover", "Demand strength."),
    E("USB9WHYL Index",   "eco", "Treasury Auctions", "13-Week Bill",
      "13W T-Bill High Yield", "Stop-out yield."),
    E("USB9DBAP Index",   "eco", "Treasury Auctions", "13-Week Bill",
      "13W T-Bill Dealer Award", "Dealer absorption."),
    E("USB9IBAP Index",   "eco", "Treasury Auctions", "13-Week Bill",
      "13W T-Bill Indirect Award", "Foreign demand."),
    # 3-Month Bill
    E("USB3MBC Index",    "eco", "Treasury Auctions", "3-Month Bill",
      "3M T-Bill Bid-to-Cover", "Demand strength."),
    E("USB3MTA Index",    "eco", "Treasury Auctions", "3-Month Bill",
      "3M T-Bill Total Allotted", "Total amount auctioned."),
    E("USB3DBA Index",    "eco", "Treasury Auctions", "3-Month Bill",
      "3M T-Bill Dealer Award", "Dealer absorption."),
    E("USB3IBA Index",    "eco", "Treasury Auctions", "3-Month Bill",
      "3M T-Bill Indirect Award", "Foreign demand."),
    # 6-Month Bill
    E("USB6MBC Index",    "eco", "Treasury Auctions", "6-Month Bill",
      "6M T-Bill Bid-to-Cover", "Demand strength."),
    E("USB6MTA Index",    "eco", "Treasury Auctions", "6-Month Bill",
      "6M T-Bill Total Allotted", "Auction size."),
    E("USB6DBA Index",    "eco", "Treasury Auctions", "6-Month Bill",
      "6M T-Bill Dealer Award", "Dealer absorption."),
    E("USB6IBA Index",    "eco", "Treasury Auctions", "6-Month Bill",
      "6M T-Bill Indirect Award", "Foreign demand."),
    # 12-Month Bill
    E("USB12MBC Index",   "eco", "Treasury Auctions", "12-Month Bill",
      "12M T-Bill Bid-to-Cover", "Demand strength."),
    E("USB12MTA Index",   "eco", "Treasury Auctions", "12-Month Bill",
      "12M T-Bill Total Allotted", "Auction size."),
    E("USB12DB Index",    "eco", "Treasury Auctions", "12-Month Bill",
      "12M T-Bill Dealer Award", "Dealer absorption."),
    E("USB12IB Index",    "eco", "Treasury Auctions", "12-Month Bill",
      "12M T-Bill Indirect Award", "Foreign demand."),

    # =========================================================================
    # TREASURY AUCTIONS — Notes
    # =========================================================================
    # 2Y Note (TU)
    E("USB2YBC Index",    "eco", "Treasury Auctions", "2Y Note (TU)",
      "2Y Note Bid-to-Cover", "Direct TU signal — auction tail moves TU 3-8bp."),
    E("USB2YTA Index",    "eco", "Treasury Auctions", "2Y Note (TU)",
      "2Y Note Total Allotted", "Auction size."),
    E("USB2DBA Index",    "eco", "Treasury Auctions", "2Y Note (TU)",
      "2Y Note Dealer Award", "Dealer absorption."),
    E("USB2IBA Index",    "eco", "Treasury Auctions", "2Y Note (TU)",
      "2Y Note Indirect Award", "Foreign demand for short-end UST."),
    # 3Y Note
    E("USN3YBC Index",    "eco", "Treasury Auctions", "3Y Note",
      "3Y Note Bid-to-Cover", "Belly-of-curve demand strength."),
    E("USN3YTA Index",    "eco", "Treasury Auctions", "3Y Note",
      "3Y Note Total Allotted", "Auction size."),
    E("USN3DBA Index",    "eco", "Treasury Auctions", "3Y Note",
      "3Y Note Dealer Award", "Dealer absorption."),
    E("USN3IBA Index",    "eco", "Treasury Auctions", "3Y Note",
      "3Y Note Indirect Award", "Foreign demand."),
    # 5Y Note (FV)
    E("USB5YBC Index",    "eco", "Treasury Auctions", "5Y Note (FV)",
      "5Y Note Bid-to-Cover", "Direct FV signal — belly demand."),
    E("USB5YTA Index",    "eco", "Treasury Auctions", "5Y Note (FV)",
      "5Y Note Total Allotted", "Auction size."),
    E("USB5DBA Index",    "eco", "Treasury Auctions", "5Y Note (FV)",
      "5Y Note Dealer Award", "Dealer absorption."),
    E("USB5IBA Index",    "eco", "Treasury Auctions", "5Y Note (FV)",
      "5Y Note Indirect Award", "Foreign demand."),
    # 7Y Note
    E("USB7YBC Index",    "eco", "Treasury Auctions", "7Y Note",
      "7Y Note Bid-to-Cover", "Belly demand."),
    E("USB7YTA Index",    "eco", "Treasury Auctions", "7Y Note",
      "7Y Note Total Allotted", "Auction size."),
    E("USB7DBA Index",    "eco", "Treasury Auctions", "7Y Note",
      "7Y Note Dealer Award", "Dealer absorption."),
    E("USB7IBA Index",    "eco", "Treasury Auctions", "7Y Note",
      "7Y Note Indirect Award", "Foreign demand."),
    # 10Y Note (TY)
    E("USN10YBC Index",   "eco", "Treasury Auctions", "10Y Note (TY)",
      "10Y Note Bid-to-Cover", "Direct TY signal — most-watched UST auction."),
    E("USN10YTA Index",   "eco", "Treasury Auctions", "10Y Note (TY)",
      "10Y Note Total Allotted", "Auction size."),
    E("USN1DBA Index",    "eco", "Treasury Auctions", "10Y Note (TY)",
      "10Y Note Dealer Award", "Dealer absorption."),
    E("USN1IBA Index",    "eco", "Treasury Auctions", "10Y Note (TY)",
      "10Y Note Indirect Award", "Foreign demand for benchmark UST."),
    # 20Y Note
    E("USN20YBC Index",   "eco", "Treasury Auctions", "20Y Note",
      "20Y Note Bid-to-Cover", "Long-end belly demand."),
    E("USN20YTA Index",   "eco", "Treasury Auctions", "20Y Note",
      "20Y Note Total Allotted", "Auction size."),
    E("USN2DBAP Index",   "eco", "Treasury Auctions", "20Y Note",
      "20Y Note Dealer Award", "Dealer absorption."),
    E("USN2IBAP Index",   "eco", "Treasury Auctions", "20Y Note",
      "20Y Note Indirect Award", "Foreign demand."),

    # =========================================================================
    # TREASURY AUCTIONS — 30Y Bond (AUL signal)
    # =========================================================================
    E("USBD30YB Index",   "eco", "Treasury Auctions", "30Y Bond (AUL)",
      "30Y Bond Bid-to-Cover", "Direct AUL signal — long-end risk premium gauge."),
    E("USBD30YT Index",   "eco", "Treasury Auctions", "30Y Bond (AUL)",
      "30Y Bond Total Allotted", "Auction size."),
    E("USBDDBA Index",    "eco", "Treasury Auctions", "30Y Bond (AUL)",
      "30Y Bond Dealer Award", "Dealer absorption."),
    E("USBDIBA Index",    "eco", "Treasury Auctions", "30Y Bond (AUL)",
      "30Y Bond Indirect Award", "Foreign demand for long-end UST."),

    # =========================================================================
    # TREASURY AUCTIONS — TIPS
    # =========================================================================
    E("TII1BIDC Index",   "eco", "Treasury Auctions", "TIPS",
      "TIPS Bid-to-Cover", "Inflation-protected demand."),
    E("TII1HYLD Index",   "eco", "Treasury Auctions", "TIPS",
      "TIPS Stop-out Real Yield", "Real yield + breakeven decomposition input."),
    E("TII1DBA Index",    "eco", "Treasury Auctions", "TIPS",
      "TIPS Dealer Award", "Dealer absorption."),
    E("TII1IBA Index",    "eco", "Treasury Auctions", "TIPS",
      "TIPS Indirect Award", "Foreign demand for breakevens."),

    # =========================================================================
    # TREASURY AUCTIONS — FRN
    # =========================================================================
    E("FRN2BITC Index",   "eco", "Treasury Auctions", "Floating-Rate Note",
      "UST 2-Year FRN Bid-to-Cover Ratio",
      "FRN demand (priced off 13W bill auction +/- spread)."),
    E("FRN2HIDM Index",   "eco", "Treasury Auctions", "Floating-Rate Note",
      "UST 2-Year FRN High Discount Margin",
      "Spread to 13W bill — risk premium for FRN holders."),
    E("FRN2DPCA Index",   "eco", "Treasury Auctions", "Floating-Rate Note",
      "US 2Y FRN Dealer Purchased Allocation", "Dealer absorption."),
    E("FRN2IPCA Index",   "eco", "Treasury Auctions", "Floating-Rate Note",
      "US 2Y FRN Indirect Purchaser Allocation", "Foreign / asset-manager demand."),

    # =========================================================================
    # ENERGY (price/activity only — no inventory per user)
    # =========================================================================
    E("USCRWTIC Index",   "energy_extras", "Energy", "Crude Prices",
      "Cushing OK WTI Spot", "US benchmark crude price; CPI energy component driver."),
    E("EUCRBRDT Index",   "energy_extras", "Energy", "Crude Prices",
      "Brent Dated Spot", "Global benchmark crude."),
    E("CO1 Comdty",       "energy_extras", "Energy", "Crude Prices",
      "Brent 1st-month future", "Tradable benchmark."),
    E("FN1 Comdty",       "energy_extras", "Energy", "Natural Gas",
      "Henry Hub Natural Gas 1st-month future",
      "US NG benchmark — heating-degree-day driver of CPI."),
    E("BAKEOIL Index",    "energy_extras", "Energy", "Production Activity",
      "Baker Hughes US Crude Oil Rig Count",
      "Activity → production capacity in 6-12 months."),
    E("BAKEGAS Index",    "energy_extras", "Energy", "Production Activity",
      "Baker Hughes US Natural Gas Rig Count",
      "Same for NG."),
    E("BAKETOT Index",    "energy_extras", "Energy", "Production Activity",
      "Baker Hughes US Total Oil & Gas Rig Count", "Aggregate."),
    E("DOIDCRUD Index",   "eco", "Energy", "DOE Implied Output",
      "DOE Crude Oil Output Implied Daily", "US crude production."),
    E("DOIDDIST Index",   "eco", "Energy", "DOE Implied Output",
      "DOE Distillate Fuel Output Implied", "Distillate production."),
    E("DOIDMOGA Index",   "eco", "Energy", "DOE Implied Output",
      "DOE Motor Gasoline Total Output Implied", "Gasoline production."),
    E("DOEAUTIL Index",   "eco", "Energy", "Refining",
      "DOE Change in Refining Capacity Utilization",
      "Refinery util % — affects gasoline supply."),
    E("DOSFCOCY Index",   "eco", "Energy", "DOE Forecasts",
      "DOE STEO Crude Oil Current-Year Forecast",
      "Official US oil-price forecast (current year)."),
    E("DOSFCOFY Index",   "eco", "Energy", "DOE Forecasts",
      "DOE STEO Crude Oil Forward-Year Forecast", "Next-year forecast."),
    E("DOSFNGCY Index",   "eco", "Energy", "DOE Forecasts",
      "DOE STEO Natural Gas Current-Year Forecast", "NG current-year forecast."),
    E("DOSFNGFY Index",   "eco", "Energy", "DOE Forecasts",
      "DOE STEO Natural Gas Forward-Year Forecast", "NG next-year forecast."),
    E("OPCRSAUD Index",   "energy_extras", "Energy", "OPEC Production",
      "OPEC Saudi Arabia crude production", "Largest swing producer."),
    E("OPCRIRAN Index",   "energy_extras", "Energy", "OPEC Production",
      "OPEC Iran crude production", "Sanction-affected supply."),
    E("OPCRIRAQ Index",   "energy_extras", "Energy", "OPEC Production",
      "OPEC Iraq crude production", "Major OPEC contributor."),
    E("OPCRUAE Index",    "energy_extras", "Energy", "OPEC Production",
      "OPEC UAE crude production", "Significant OPEC member."),
    E("OPCRTOTL Index",   "energy_extras", "Energy", "OPEC Production",
      "OPEC Total crude production", "Aggregate OPEC supply."),

    # =========================================================================
    # AGRICULTURE — Food CPI inputs
    # =========================================================================
    E("CATTLE7P Index",   "eco", "Agriculture", "Cattle on Feed",
      "NASS Cattle on Feed Total", "Beef-supply proxy → meat CPI."),
    E("CATTLEMP Index",   "eco", "Agriculture", "Cattle on Feed",
      "NASS Cattle on Feed All States", "Cross-check supply."),
    E("CATTLEPP Index",   "eco", "Agriculture", "Cattle on Feed",
      "NASS Cattle on Feed All States (alt)", "Alt formulation."),
    E("COLDBEEF Index",   "eco", "Agriculture", "Cold Storage",
      "USDA Monthly Cold Storage Beef", "Beef-supply pipeline."),
    E("COLDPORK Index",   "eco", "Agriculture", "Cold Storage",
      "USDA Monthly Cold Storage Pork", "Pork supply."),
    E("COLDPOUL Index",   "eco", "Agriculture", "Cold Storage",
      "USDA Monthly Cold Storage Poultry", "Poultry supply."),
    E("COLDTOPK Index",   "eco", "Agriculture", "Cold Storage",
      "USDA Monthly Cold Storage Total", "Aggregate meat-supply gauge."),
    E("COWSTOTT Index",   "eco", "Agriculture", "Dairy",
      "USDA Monthly Total Milk Production", "Dairy supply → dairy-CPI driver."),
    E("LIVERMLY Index",   "eco", "Agriculture", "Livestock Slaughter",
      "USDA Livestock Slaughter Commercial", "Meat throughput → near-term meat CPI."),
    E("GRINCORN Index",   "eco", "Agriculture", "Grain Inspections",
      "USDA Corn Export Grain Inspections", "Export demand for corn."),
    E("GRINSOYB Index",   "eco", "Agriculture", "Grain Inspections",
      "USDA Soybeans Grain Export Inspections", "Soybean exports."),
    E("GRINWHET Index",   "eco", "Agriculture", "Grain Inspections",
      "USDA Wheat Grain Export Inspections", "Wheat exports."),
    E("CUSEENDS Index",   "eco", "Agriculture", "WASDE — US Corn",
      "USDA WASDE US Corn Ending Stocks", "Tighter stocks → corn price → food CPI."),
    E("CUSEEXPO Index",   "eco", "Agriculture", "WASDE — US Corn",
      "USDA WASDE US Corn Exports", "Export demand."),
    E("CUSEPROD Index",   "eco", "Agriculture", "WASDE — US Corn",
      "USDA WASDE US Corn Production", "Supply side."),
    E("CUSEYIEL Index",   "eco", "Agriculture", "WASDE — US Corn",
      "USDA WASDE US Corn Yield", "Per-acre productivity."),
    E("GUSEESCP Index",   "eco", "Agriculture", "WASDE — World",
      "USDA WASDE World Corn Ending Stocks", "Global tightness measure."),
    E("GUSEPRCP Index",   "eco", "Agriculture", "WASDE — World",
      "USDA WASDE World Corn Production", "Global supply."),
    E("GUSEESSP Index",   "eco", "Agriculture", "WASDE — World",
      "USDA WASDE World Soybeans Ending Stocks", "Global soy tightness."),
    E("GUSEPRSP Index",   "eco", "Agriculture", "WASDE — World",
      "USDA WASDE World Soybeans Production", "Global soy supply."),
    E("GUSEESWP Index",   "eco", "Agriculture", "WASDE — World",
      "USDA WASDE World Wheat Ending Stocks", "Global wheat tightness."),
    E("GUSEPRWP Index",   "eco", "Agriculture", "WASDE — World",
      "USDA WASDE World Wheat Production", "Global wheat supply."),
    E("GUSEESTP Index",   "eco", "Agriculture", "WASDE — World",
      "USDA WASDE World Cotton Ending Stocks", "Global cotton tightness."),
    E("GUSEPRTP Index",   "eco", "Agriculture", "WASDE — World",
      "USDA WASDE World Cotton Production", "Global cotton supply."),
    E("CORADDGS Index",   "eco", "Agriculture", "Specialty",
      "US Distillers Dried Grains with Solubles (DDGS)",
      "Ethanol byproduct — feed input."),
    E("CORATOTF Index",   "eco", "Agriculture", "Specialty",
      "US Corn Consumption for Fuel Alcohol",
      "Ethanol demand — affects corn/gasoline."),
    E("AVFO1000 Index",   "eco", "Agriculture", "Fats & Oils",
      "US Fats and Oils Soybeans Crushed", "Soy crush activity."),
    E("AVFO1001 Index",   "eco", "Agriculture", "Fats & Oils",
      "US Fats and Oils Soybeans Crude Oil", "Soy oil production."),
    E("AVFO1002 Index",   "eco", "Agriculture", "Fats & Oils",
      "US Fats and Oils Soybean Crude Oil Stocks", "Soy oil supply."),

    # =========================================================================
    # VOLATILITY
    # =========================================================================
    E("MOVE Index",       "vol_indices", "Volatility", "Bond / Rate Vol",
      "ML Treasury Options Volatility (MOVE)",
      "#1 bond-vol gauge. Used for sizing UST trades and risk regime ID."),
    E("SRVIX Index",      "vol_indices", "Volatility", "Bond / Rate Vol",
      "CBOE 1Y Swap Rate Volatility (SRVIX)",
      "#1 STIR-vol gauge. Spike = STIR option positioning shift."),
    E("VIX Index",        "vol_indices", "Volatility", "Equity Vol",
      "CBOE S&P 500 30d Vol (VIX)", "Risk-on/off; bonds bid when VIX rises."),
    E("VVIX Index",       "vol_indices", "Volatility", "Equity Vol",
      "CBOE Vol of VIX (VVIX)", "2nd-derivative risk regime."),
    E("VXN Index",        "vol_indices", "Volatility", "Equity Vol",
      "CBOE Nasdaq-100 Vol (VXN)", "Tech / duration-sensitive equity vol."),
    E("RVX Index",        "vol_indices", "Volatility", "Equity Vol",
      "CBOE Russell 2000 Vol (RVX)", "Small-cap / credit-stress proxy."),
    E("V3M Index",        "vol_indices", "Volatility", "Equity Vol",
      "CBOE 3M S&P Vol (V3M)", "Equity vol term-slope (vs VIX 1M)."),
    E("SKEW Index",       "vol_indices", "Volatility", "Equity Vol",
      "CBOE Skew Index", "Tail-risk barometer; jumps before bond rallies."),
    E("OVX Index",        "vol_indices", "Volatility", "Commodity Vol",
      "CBOE Crude Oil ETF Vol (OVX)", "Oil vol → CPI vol → STIR repricing risk."),
    E("GVZ Index",        "vol_indices", "Volatility", "Commodity Vol",
      "CBOE Gold ETF Vol (GVZ)", "Real-rate / safe-haven vol."),
    E("VXSLV Index",      "vol_indices", "Volatility", "Commodity Vol",
      "CBOE Silver ETF Vol (VXSLV)", "Industrial-monetary metal vol."),
    E("EURUSDV1M Curncy", "vol_indices", "Volatility", "FX Vol",
      "EURUSD 1M Implied Vol", "EU-rates FX vol."),
    E("GBPUSDV1M Curncy", "vol_indices", "Volatility", "FX Vol",
      "GBPUSD 1M Implied Vol", "UK-rates FX vol."),
    E("USDJPYV1M Curncy", "vol_indices", "Volatility", "FX Vol",
      "USDJPY 1M Implied Vol", "Carry-trade unwind detector."),
    E("CVIX Index",       "vol_indices", "Volatility", "FX Vol",
      "JPM EM-FX Vol Composite (CVIX)", "EM FX stress."),

    # =========================================================================
    # CREDIT
    # =========================================================================
    E("US_CDS_EUR_SR_5Y_D14_Corp", "credit", "Credit", "US Sovereign",
      "US Sovereign 5Y CDS (EUR-denominated)",
      "Sovereign credit risk; debt-ceiling stress signal."),
    E("CDX_IG_CDSI_GEN_5Y_Corp",   "credit", "Credit", "IG Corporate",
      "CDX North America IG 5Y (125 names)",
      "IG credit conditions; widens before recessions."),
    E("CDX_HY_CDSI_GEN_5Y_Corp",   "credit", "Credit", "HY Corporate",
      "CDX North America HY 5Y (100 names)",
      "HY credit; risk-on/off proxy."),
    E("LF98OAS Index",   "credit", "Credit", "HY Corporate",
      "Bloomberg US Corp HY OAS",
      "HY OAS in bp; credit-cycle indicator → curve."),
    E("LUACOAS Index",   "credit", "Credit", "IG Corporate",
      "Bloomberg US Aggregate Credit OAS",
      "IG OAS; flight-to-quality signal."),
    E("LP01OAS Index",   "credit", "Credit", "Pan-Euro Cross-Reference",
      "Bloomberg Pan-Euro Aggregate Corp OAS",
      "Cross-reference for global IG."),

    # =========================================================================
    # FX (USD pairs — abbreviated; all share same analytical theme)
    # =========================================================================
    E("EURUSD Curncy", "fx", "FX", "G10",
      "EUR per USD",
      "(FDTR-EUDR1T) drives this; SRA-ER spread proxy."),
    E("GBPUSD Curncy", "fx", "FX", "G10",
      "GBP per USD",
      "(FDTR-UKBRBASE) drives; SRA-SON proxy."),
    E("USDJPY Curncy", "fx", "FX", "G10",
      "USD per JPY",
      "(FDTR-BoJ) — biggest carry pair."),
    E("USDCHF Curncy", "fx", "FX", "G10",
      "USD per CHF",
      "(FDTR-SNB); safe-haven flows."),
    E("USDCAD Curncy", "fx", "FX", "G10",
      "USD per CAD",
      "(FDTR-CABROVER); oil-FX."),
    E("AUDUSD Curncy", "fx", "FX", "G10",
      "AUD per USD",
      "(FDTR-RBA); commodity-FX."),
    E("NZDUSD Curncy", "fx", "FX", "G10",
      "NZD per USD",
      "(FDTR-RBNZ)."),
    E("USDSEK Curncy", "fx", "FX", "G10",
      "USD per SEK", "G10 — Riksbank-rate sensitive."),
    E("USDNOK Curncy", "fx", "FX", "G10",
      "USD per NOK", "G10; oil-linked Norges Bank."),
    E("USDARS Curncy", "fx", "FX", "EM",
      "USD per Argentine Peso", "Argentine FX stress; sovereign-credit indicator."),
    E("USDBRL Curncy", "fx", "FX", "EM",
      "USD per Brazilian Real", "Selic-rate sensitive; rate-differential channel."),
    E("USDCLP Curncy", "fx", "FX", "EM",
      "USD per Chilean Peso", "Copper-linked commodity FX."),
    E("USDCNY Curncy", "fx", "FX", "EM",
      "USD per Chinese Yuan (onshore)", "PBoC-fix sensitive; reserve-asset signal."),
    E("USDCOP Curncy", "fx", "FX", "EM",
      "USD per Colombian Peso", "Oil-linked Latam FX."),
    E("USDCZK Curncy", "fx", "FX", "EM",
      "USD per Czech Koruna", "CNB-sensitive; CEE rate channel."),
    E("USDEGP Curncy", "fx", "FX", "EM",
      "USD per Egyptian Pound", "Frontier-market FX stress proxy."),
    E("USDHUF Curncy", "fx", "FX", "EM",
      "USD per Hungarian Forint", "MNB-sensitive; CEE rate channel."),
    E("USDIDR Curncy", "fx", "FX", "EM",
      "USD per Indonesian Rupiah", "Asia EM FX; commodity-linked."),
    E("USDILS Curncy", "fx", "FX", "EM",
      "USD per Israeli Shekel", "Bank of Israel rate-sensitive."),
    E("USDINR Curncy", "fx", "FX", "EM",
      "USD per Indian Rupee", "RBI-sensitive; oil-import channel."),
    E("USDKRW Curncy", "fx", "FX", "EM",
      "USD per Korean Won", "BoK-sensitive; tech-export linked."),
    E("USDMXN Curncy", "fx", "FX", "EM",
      "USD per Mexican Peso", "Banxico-sensitive; carry currency."),
    E("USDPEN Curncy", "fx", "FX", "EM",
      "USD per Peruvian Sol", "Copper-linked Latam FX."),
    E("USDPHP Curncy", "fx", "FX", "EM",
      "USD per Philippine Peso", "BSP-sensitive Asia FX."),
    E("USDPLN Curncy", "fx", "FX", "EM",
      "USD per Polish Zloty", "NBP-sensitive; CEE rate channel."),
    E("USDSAR Curncy", "fx", "FX", "EM (pegged)",
      "USD per Saudi Riyal", "USD-peg; oil-funding indicator."),
    E("USDSGD Curncy", "fx", "FX", "EM",
      "USD per Singapore Dollar", "MAS slope-managed FX."),
    E("USDTHB Curncy", "fx", "FX", "EM",
      "USD per Thai Baht", "BoT-sensitive Asia FX."),
    E("USDTRY Curncy", "fx", "FX", "EM",
      "USD per Turkish Lira", "CBRT-sensitive; high-vol EM."),
    E("USDZAR Curncy", "fx", "FX", "EM",
      "USD per South African Rand", "SARB-sensitive; commodity-linked."),

    # =========================================================================
    # EQUITY INDICES
    # =========================================================================
    E("SPX Index",     "equity_indices", "Equity Indices", "US Major",
      "S&P 500", "Risk-on/off composite."),
    E("INDU Index",    "equity_indices", "Equity Indices", "US Major",
      "Dow Jones Industrial Average", "Cyclical exposure."),
    E("NDX Index",     "equity_indices", "Equity Indices", "US Major",
      "Nasdaq 100", "Long-duration / rate-sensitive."),
    E("SPY US Equity", "equity_indices", "Equity Indices", "ETF Reference",
      "SPDR S&P 500 ETF", "Cash equity reference."),

    # =========================================================================
    # POSITIONING — CFTC COT (FI products)
    # Each product has 11 fields (futures) or 10 (options): COL, COS, NCL, NCS,
    # NCN, NCP, NRL, NRS, OIN, TLL, TLS — shown collectively.
    # =========================================================================
    E("IMM13* (11 fields)",  "xcot", "Positioning (CFTC COT)", "STIR — Eurodollar Legacy",
      "CME 3-Month Eurodollars positioning",
      "Legacy STIR positioning (Eurodollar = pre-SOFR benchmark). Extreme NCN net = contrarian setup."),
    E("IMMO3* (10 fields)",  "xcot", "Positioning (CFTC COT)", "STIR Options",
      "Options on CME 3-Month Eurodollars",
      "STIR options positioning (skew, gamma)."),
    E("CBT42* (11 fields)",  "xcot", "Positioning (CFTC COT)", "UST 2Y (TU)",
      "CBOT 2-YR US Treasury Note positioning",
      "Front-end positioning. Speculator extreme net = mean-reversion signal for TU."),
    E("CBT55* (11 fields)",  "xcot", "Positioning (CFTC COT)", "UST 5Y (FV)",
      "CBOT 5-YR US Treasury Notes positioning",
      "Belly positioning."),
    E("CBT4T* (11 fields)",  "xcot", "Positioning (CFTC COT)", "UST 10Y (TY)",
      "CBOT 10-YR US Treasury Notes positioning",
      "Most-watched UST positioning. Net positioning extremes = curve-trade contrarian setup."),
    E("CBT3T* (11 fields)",  "xcot", "Positioning (CFTC COT)", "UST 30Y T-Bond",
      "CBOT 30-YR US Treasury Bonds positioning",
      "Long-end positioning."),
    E("CBT3B* (11 fields)",  "xcot", "Positioning (CFTC COT)", "UST Ultra (AUL)",
      "CBOT Ultra-Long US Treasury Bonds positioning",
      "Convexity-sensitive long-end positioning."),
    E("CBTO2* (10 fields)",  "xcot", "Positioning (CFTC COT)", "UST 2Y Options",
      "Options on CBOT 2-YR T-Note", "Front-end options positioning."),
    E("CBTP5* (10 fields)",  "xcot", "Positioning (CFTC COT)", "UST 5Y Options",
      "Options on CBOT 5-YR T-Note", "Belly options positioning."),
    E("CBTPT* (10 fields)",  "xcot", "Positioning (CFTC COT)", "UST 10Y Options",
      "Options on CBOT 10-YR T-Note", "10Y options positioning (most-traded UST options)."),
    E("CBTOT* (10 fields)",  "xcot", "Positioning (CFTC COT)", "UST 30Y Options",
      "Options on CBOT 30-YR T-Bond", "Long-end options positioning."),
    E("CBTOB* (10 fields)",  "xcot", "Positioning (CFTC COT)", "UST Ultra Options",
      "Options on CBOT Ultra-Long T-Bond", "Convexity-trade options positioning."),
]


# Field-code legend for the positioning entries
COT_FIELD_LEGEND = [
    ("COL / COS",  "Commercial Long / Short — hedgers (e.g. asset managers, dealers)"),
    ("NCL / NCS",  "Non-Commercial Long / Short — speculators / leveraged funds"),
    ("NCN",        "Non-Commercial Net = NCL − NCS (key positioning gauge)"),
    ("NCP",        "NC Net % of Open Interest"),
    ("NRL / NRS",  "Non-Reportable Long / Short — small specs"),
    ("OIN",        "Open Interest"),
    ("TLL / TLS",  "Total Long / Short — sum of all reportables"),
]


def get_inventory_dataframe():
    """Return the inventory as a pandas DataFrame for display/filtering."""
    import pandas as pd
    return pd.DataFrame(US_TICKERS)


def get_category_summary():
    """Return per-category counts."""
    import pandas as pd
    df = get_inventory_dataframe()
    return df.groupby("category").size().to_dict()
